Integrate Firebase
rootstrap/the-hive-react-native pull request #5
Opened 2023-03-03 20:55 UTC by jpirazusta

### Pull request type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): Config

---

### Description

Integrated Firebase for the different environments for android and iOS.

2023-03-03 20:57 UTC, ManuViola77 approved these changes
👏🏻

2023-03-03 22:49 UTC, marcos09 requested changes
I think you added the google-services key. Please remove it, and I'll approve the PR.

2023-03-03 22:49 UTC, marcos09 commented on android/app/src/develop/google-services.json
> +{
I think you added this file before adding the path to the gitignore. Could you remove it?

2023-03-04 00:50 UTC, jpirazusta commented on android/app/src/develop/google-services.json
> +{
I don't know why the development one is appearing, since all are in gitignore. I removed it

2023-03-06 12:20 UTC, marcos09 approved these changes

2023-03-06 14:28 UTC, merged